singleQuote: true
semi: false
printWidth: 100
trailingComma: none
importOrder:
  [
    '^(react/(.*)$)|^(react$)',
    '^@/types/(.*)$',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '^@/env(.*)$',
    '^@/types$',
    '^@/config/(.*)$',
    '^@renderer/store(.*)$',
    '^@renderer/lib/(.*)$',
    '^@renderer/hooks/(.*)$',
    '^@renderer/components/ui/(.*)$',
    '^@renderer/components/(.*)$',
    '^@renderer/styles/(.*)$',
    '',
    '^[./]'
  ]
plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss']
